# Generated by Django 5.1.4 on 2025-01-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age_now',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
