# Generated by Django 5.1.4 on 2025-01-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_age_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_pic',
            field=models.ImageField(default='static/img/none.bmp', upload_to='static/img'),
        ),
    ]
