# Generated by Django 5.1.4 on 2025-01-07 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0001_initial'),
        ('users', '0003_alter_user_avatar_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='little_about',
            field=models.TextField(default=123, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_speed', models.PositiveIntegerField()),
                ('step_count', models.PositiveIntegerField()),
                ('some_one', models.IntegerField()),
                ('number_of_points', models.PositiveIntegerField(default=0)),
                ('played_games', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.game')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
