# Generated by Django 5.1.4 on 2025-03-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message_to_user_alter_message_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_anonim',
            field=models.BooleanField(default=False),
        ),
    ]
