# Generated by Django 5.1.4 on 2025-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_message_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='message',
            name='time_send',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
