# Generated by Django 5.1.4 on 2025-04-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_message_picture_message_time_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img'),
        ),
    ]
