# Generated by Django 5.1.4 on 2025-04-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_message_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/img/message'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_pic',
            field=models.ImageField(default='static/img/avatar/none.bmp', upload_to='static/img/avatar'),
        ),
    ]
